name: Feature Request
description: Suggest a new feature or enhancement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your feature suggestion! Please check the [Roadmap](https://github.com/itsDNNS/docsight/wiki/Roadmap) first to see if it's already planned.

  - type: textarea
    id: problem
    attributes:
      label: Problem or Use Case
      description: What problem would this feature solve? Is your feature request related to a specific issue?
      placeholder: |
        I'm frustrated when...
        It would be helpful if...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the feature or enhancement you'd like to see
      placeholder: |
        Add a button that...
        Integrate with X to...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: |
        I tried using X but...
        Another approach could be...

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Nice to have
        - Would be very helpful
        - Critical for my use case
    validations:
      required: true

  - type: checkboxes
    id: contribute
    attributes:
      label: Contribution
      description: Are you willing to help implement this feature?
      options:
        - label: I can help with testing
        - label: I can contribute code (PR)
        - label: I can help with documentation

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or mockups about the feature request
      placeholder: Here's a screenshot of how this works in another tool...
