"""Theme registry helpers and built-in DOCSight theme definitions."""

from __future__ import annotations

import logging
import os
import shutil
from typing import Any

from .module_download import (
    fetch_registry as _fetch_registry,
    download_github_directory,
    is_trusted_url,
)
from .path_safety import safe_child_file

log = logging.getLogger("docsis.themes")

# Re-export for backward compatibility (used by tests)
_is_trusted_url = is_trusted_url

# Built-in themes are application-owned data, not plugin modules.  Keep their
# metadata and CSS tokens together so startup does not need wrapper module
# directories or per-theme manifests for the shipped palettes.
BUILTIN_THEMES: tuple[dict[str, Any], ...] = ({'id': 'docsight.theme_amber_terminal',
  'name': 'Amber Terminal',
  'description': 'Warm amber on black — classic CRT monitor nostalgia',
  'version': '1.0.0',
  'author': 'itsDNNS',
  'minAppVersion': '2026.2',
  'theme_data': {'meta': {'family': 'dark-first'},
                 'dark': {'--bg': '#0c0800',
                          '--surface': '#120e04',
                          '--card': '#161008',
                          '--card-border': 'rgba(255, 176, 0, 0.15)',
                          '--text': '#ffb000',
                          '--text-secondary': '#cc8c00',
                          '--muted': '#806000',
                          '--good': '#ffcc00',
                          '--warn': '#ff8800',
                          '--crit': '#ff3300',
                          '--accent': '#ffb000',
                          '--accent-hover': '#ffc840',
                          '--accent-muted': 'rgba(255, 176, 0, 0.12)',
                          '--info': '#ffcc66',
                          '--input-border': 'rgba(255, 176, 0, 0.2)',
                          '--overlay': 'rgba(0, 0, 0, 0.8)',
                          '--hover-bg': 'rgba(255, 176, 0, 0.06)',
                          '--void': '#080400',
                          '--void-deep': '#040200',
                          '--elevated': '#1e1610',
                          '--hover': '#261c14',
                          '--amethyst': '#ffb000',
                          '--amethyst-light': '#ffc840',
                          '--sapphire': '#ffcc66',
                          '--glass-bg': 'rgba(12, 8, 0, 0.9)',
                          '--glass-border': 'rgba(255, 176, 0, 0.1)',
                          '--font-sans': "'Courier New', 'Consolas', monospace",
                          '--font-mono': "'Courier New', 'Consolas', monospace"},
                 'light': {'--bg': '#fff8e8',
                           '--surface': '#fff8e8',
                           '--card': '#f5ead0',
                           '--card-border': '#e0c890',
                           '--text': '#3d2800',
                           '--text-secondary': '#6b4d10',
                           '--muted': '#a08040',
                           '--good': '#8a7000',
                           '--warn': '#b05c00',
                           '--crit': '#cc2200',
                           '--accent': '#a06800',
                           '--accent-hover': '#855500',
                           '--accent-muted': 'rgba(160, 104, 0, 0.1)',
                           '--info': '#8a7000',
                           '--input-border': '#e0c890',
                           '--overlay': 'rgba(0, 0, 0, 0.4)',
                           '--hover-bg': 'rgba(160, 104, 0, 0.05)',
                           '--void': '#fff8e8',
                           '--void-deep': '#f5ead0',
                           '--elevated': '#eddcb8',
                           '--hover': '#e0c890',
                           '--amethyst': '#a06800',
                           '--amethyst-light': '#b87c10',
                           '--sapphire': '#8a7000',
                           '--glass-bg': 'rgba(255, 248, 232, 0.85)',
                           '--glass-border': 'rgba(160, 104, 0, 0.08)',
                           '--font-sans': "'Courier New', 'Consolas', monospace",
                           '--font-mono': "'Courier New', 'Consolas', monospace"}}},
 {'id': 'docsight.theme_catppuccin_mocha',
  'name': 'Catppuccin Mocha',
  'description': 'Creamy mauves and blue-greens inspired by the popular Catppuccin palette',
  'version': '1.0.0',
  'author': 'itsDNNS',
  'minAppVersion': '2026.2',
  'theme_data': {'meta': {'family': 'community-favorite', 'collection': 'community'},
                 'dark': {'--bg': '#1e1e2e',
                          '--surface': '#181825',
                          '--card': '#313244',
                          '--card-border': 'rgba(203, 166, 247, 0.12)',
                          '--text': '#cdd6f4',
                          '--text-secondary': '#bac2de',
                          '--muted': '#6c7086',
                          '--good': '#a6e3a1',
                          '--warn': '#f9e2af',
                          '--crit': '#f38ba8',
                          '--accent': '#cba6f7',
                          '--accent-hover': '#b4befe',
                          '--accent-muted': 'rgba(203, 166, 247, 0.14)',
                          '--info': '#89dceb',
                          '--input-border': 'rgba(203, 166, 247, 0.18)',
                          '--overlay': 'rgba(17, 17, 27, 0.72)',
                          '--hover-bg': 'rgba(255, 255, 255, 0.04)',
                          '--void': '#11111b',
                          '--void-deep': '#0b0b12',
                          '--elevated': '#45475a',
                          '--hover': '#585b70',
                          '--amethyst': '#cba6f7',
                          '--amethyst-light': '#f5c2e7',
                          '--sapphire': '#89b4fa',
                          '--glass-bg': 'rgba(30, 30, 46, 0.84)',
                          '--glass-border': 'rgba(203, 166, 247, 0.1)'},
                 'light': {'--bg': '#eff1f5',
                           '--surface': '#ffffff',
                           '--card': '#e6e9ef',
                           '--card-border': 'rgba(114, 135, 253, 0.12)',
                           '--text': '#4c4f69',
                           '--text-secondary': '#5c5f77',
                           '--muted': '#8c8fa1',
                           '--good': '#40a02b',
                           '--warn': '#df8e1d',
                           '--crit': '#d20f39',
                           '--accent': '#8839ef',
                           '--accent-hover': '#7287fd',
                           '--accent-muted': 'rgba(136, 57, 239, 0.1)',
                           '--info': '#04a5e5',
                           '--input-border': 'rgba(136, 57, 239, 0.14)',
                           '--overlay': 'rgba(0, 0, 0, 0.35)',
                           '--hover-bg': 'rgba(136, 57, 239, 0.04)',
                           '--void': '#eff1f5',
                           '--void-deep': '#e6e9ef',
                           '--elevated': '#dce0e8',
                           '--hover': '#ccd0da',
                           '--amethyst': '#8839ef',
                           '--amethyst-light': '#ea76cb',
                           '--sapphire': '#1e66f5',
                           '--glass-bg': 'rgba(239, 241, 245, 0.86)',
                           '--glass-border': 'rgba(136, 57, 239, 0.08)'}}},
 {'id': 'docsight.theme_classic',
  'name': 'Classic',
  'description': 'The original DOCSight charcoal and purple design',
  'version': '1.0.0',
  'author': 'itsDNNS',
  'minAppVersion': '2026.2',
  'theme_data': {'meta': {'family': 'dark-first'},
                 'dark': {'--bg': '#1f2937',
                          '--surface': '#1f2937',
                          '--card': '#1f2937',
                          '--card-border': 'rgba(255, 255, 255, 0.08)',
                          '--text': '#f0f0f0',
                          '--text-secondary': '#9ca3af',
                          '--muted': '#6b7280',
                          '--good': '#10b981',
                          '--warn': '#f59e0b',
                          '--crit': '#ef4444',
                          '--accent': '#a855f7',
                          '--accent-hover': '#9333ea',
                          '--accent-muted': 'rgba(168, 85, 247, 0.15)',
                          '--info': '#3b82f6',
                          '--input-border': 'rgba(255, 255, 255, 0.1)',
                          '--overlay': 'rgba(0, 0, 0, 0.6)',
                          '--hover-bg': 'rgba(255, 255, 255, 0.05)',
                          '--void': '#1f2937',
                          '--void-deep': '#111827',
                          '--elevated': '#374151',
                          '--hover': '#4b5563',
                          '--amethyst': '#a855f7',
                          '--amethyst-light': '#c084fc',
                          '--sapphire': '#3b82f6',
                          '--glass-bg': 'rgba(31, 41, 55, 0.8)',
                          '--glass-border': 'rgba(255, 255, 255, 0.08)'},
                 'light': {'--bg': '#ffffff',
                           '--surface': '#ffffff',
                           '--card': '#f9fafb',
                           '--card-border': '#e5e7eb',
                           '--text': '#111827',
                           '--text-secondary': '#6b7280',
                           '--muted': '#9ca3af',
                           '--good': '#059669',
                           '--warn': '#d97706',
                           '--crit': '#dc2626',
                           '--accent': '#9333ea',
                           '--accent-hover': '#7e22ce',
                           '--accent-muted': 'rgba(147, 51, 234, 0.1)',
                           '--info': '#2563eb',
                           '--input-border': '#e5e7eb',
                           '--overlay': 'rgba(0, 0, 0, 0.4)',
                           '--hover-bg': 'rgba(0, 0, 0, 0.03)',
                           '--void': '#ffffff',
                           '--void-deep': '#f9fafb',
                           '--elevated': '#f3f4f6',
                           '--hover': '#e5e7eb',
                           '--amethyst': '#9333ea',
                           '--amethyst-light': '#a855f7',
                           '--sapphire': '#2563eb',
                           '--glass-bg': 'rgba(255, 255, 255, 0.8)',
                           '--glass-border': 'rgba(0, 0, 0, 0.08)'}}},
 {'id': 'docsight.theme_doom',
  'name': 'Doom',
  'description': 'Dark reds, lava orange and brimstone — rip and tear',
  'version': '1.0.0',
  'author': 'itsDNNS',
  'minAppVersion': '2026.2',
  'theme_data': {'meta': {'family': 'dark-first'},
                 'dark': {'--bg': '#1a0a0a',
                          '--surface': '#241010',
                          '--card': '#2a1414',
                          '--card-border': 'rgba(255, 68, 0, 0.18)',
                          '--text': '#e8ccaa',
                          '--text-secondary': '#b89878',
                          '--muted': '#7a5c44',
                          '--good': '#4caf50',
                          '--warn': '#ff8c00',
                          '--crit': '#ff2200',
                          '--accent': '#ff4400',
                          '--accent-hover': '#ff5522',
                          '--accent-muted': 'rgba(255, 68, 0, 0.15)',
                          '--info': '#cc6600',
                          '--input-border': 'rgba(255, 68, 0, 0.22)',
                          '--overlay': 'rgba(10, 2, 2, 0.8)',
                          '--hover-bg': 'rgba(255, 68, 0, 0.08)',
                          '--void': '#100505',
                          '--void-deep': '#080202',
                          '--elevated': '#351a1a',
                          '--hover': '#402020',
                          '--amethyst': '#ff4400',
                          '--amethyst-light': '#ff6633',
                          '--sapphire': '#cc6600',
                          '--glass-bg': 'rgba(26, 10, 10, 0.88)',
                          '--glass-border': 'rgba(255, 68, 0, 0.12)'},
                 'light': {'--bg': '#fff0e6',
                           '--surface': '#fff0e6',
                           '--card': '#f5dcc8',
                           '--card-border': '#ddb89a',
                           '--text': '#3d1a0a',
                           '--text-secondary': '#6b3820',
                           '--muted': '#a07050',
                           '--good': '#2e7d32',
                           '--warn': '#c46600',
                           '--crit': '#cc1a00',
                           '--accent': '#c43500',
                           '--accent-hover': '#a02c00',
                           '--accent-muted': 'rgba(196, 53, 0, 0.1)',
                           '--info': '#995200',
                           '--input-border': '#ddb89a',
                           '--overlay': 'rgba(0, 0, 0, 0.4)',
                           '--hover-bg': 'rgba(196, 53, 0, 0.05)',
                           '--void': '#fff0e6',
                           '--void-deep': '#f5dcc8',
                           '--elevated': '#ecc8aa',
                           '--hover': '#ddb89a',
                           '--amethyst': '#c43500',
                           '--amethyst-light': '#d84800',
                           '--sapphire': '#995200',
                           '--glass-bg': 'rgba(255, 240, 230, 0.85)',
                           '--glass-border': 'rgba(196, 53, 0, 0.08)'}}},
 {'id': 'docsight.theme_dracula',
  'name': 'Dracula',
  'description': 'Electric purples and candy accents inspired by the Dracula classic',
  'version': '1.0.0',
  'author': 'itsDNNS',
  'minAppVersion': '2026.2',
  'theme_data': {'meta': {'family': 'community-favorite', 'collection': 'community'},
                 'dark': {'--bg': '#282a36',
                          '--surface': '#21222c',
                          '--card': '#303341',
                          '--card-border': 'rgba(189, 147, 249, 0.14)',
                          '--text': '#f8f8f2',
                          '--text-secondary': '#c9cbe3',
                          '--muted': '#6272a4',
                          '--good': '#50fa7b',
                          '--warn': '#f1fa8c',
                          '--crit': '#ff5555',
                          '--accent': '#bd93f9',
                          '--accent-hover': '#d6acff',
                          '--accent-muted': 'rgba(189, 147, 249, 0.16)',
                          '--info': '#8be9fd',
                          '--input-border': 'rgba(189, 147, 249, 0.18)',
                          '--overlay': 'rgba(16, 17, 23, 0.72)',
                          '--hover-bg': 'rgba(189, 147, 249, 0.08)',
                          '--void': '#1f2029',
                          '--void-deep': '#17181f',
                          '--elevated': '#3a3d4d',
                          '--hover': '#44475a',
                          '--amethyst': '#bd93f9',
                          '--amethyst-light': '#ff79c6',
                          '--sapphire': '#8be9fd',
                          '--glass-bg': 'rgba(40, 42, 54, 0.84)',
                          '--glass-border': 'rgba(189, 147, 249, 0.1)'},
                 'light': {'--bg': '#f6f4ff',
                           '--surface': '#ffffff',
                           '--card': '#ede8ff',
                           '--card-border': 'rgba(149, 104, 255, 0.14)',
                           '--text': '#2e2242',
                           '--text-secondary': '#5f537a',
                           '--muted': '#8a7fa4',
                           '--good': '#1f8f4d',
                           '--warn': '#9d8a16',
                           '--crit': '#d64545',
                           '--accent': '#7c5cff',
                           '--accent-hover': '#684ce6',
                           '--accent-muted': 'rgba(124, 92, 255, 0.1)',
                           '--info': '#1b95b8',
                           '--input-border': 'rgba(124, 92, 255, 0.14)',
                           '--overlay': 'rgba(0, 0, 0, 0.3)',
                           '--hover-bg': 'rgba(124, 92, 255, 0.05)',
                           '--void': '#f6f4ff',
                           '--void-deep': '#ede8ff',
                           '--elevated': '#e3dcff',
                           '--hover': '#d4cbff',
                           '--amethyst': '#7c5cff',
                           '--amethyst-light': '#b179ff',
                           '--sapphire': '#1b95b8',
                           '--glass-bg': 'rgba(246, 244, 255, 0.86)',
                           '--glass-border': 'rgba(124, 92, 255, 0.08)'}}},
 {'id': 'docsight.theme_gameboy',
  'name': 'GameBoy',
  'description': 'The 4 iconic green shades of the original Game Boy LCD',
  'version': '1.0.0',
  'author': 'itsDNNS',
  'minAppVersion': '2026.2',
  'theme_data': {'meta': {'family': 'dark-first'},
                 'dark': {'--bg': '#0f380f',
                          '--surface': '#1a4a1a',
                          '--card': '#1a4a1a',
                          '--card-border': 'rgba(155, 188, 15, 0.2)',
                          '--text': '#9bbc0f',
                          '--text-secondary': '#8bac0f',
                          '--muted': '#306230',
                          '--good': '#9bbc0f',
                          '--warn': '#8bac0f',
                          '--crit': '#556b2f',
                          '--accent': '#9bbc0f',
                          '--accent-hover': '#8bac0f',
                          '--accent-muted': 'rgba(155, 188, 15, 0.15)',
                          '--info': '#8bac0f',
                          '--input-border': 'rgba(155, 188, 15, 0.25)',
                          '--overlay': 'rgba(15, 56, 15, 0.8)',
                          '--hover-bg': 'rgba(155, 188, 15, 0.08)',
                          '--void': '#0a2a0a',
                          '--void-deep': '#061e06',
                          '--elevated': '#306230',
                          '--hover': '#3a7a3a',
                          '--amethyst': '#9bbc0f',
                          '--amethyst-light': '#b0d020',
                          '--sapphire': '#8bac0f',
                          '--glass-bg': 'rgba(15, 56, 15, 0.85)',
                          '--glass-border': 'rgba(155, 188, 15, 0.12)',
                          '--font-sans': "'Courier New', 'Consolas', monospace",
                          '--font-mono': "'Courier New', 'Consolas', monospace"},
                 'light': {'--bg': '#9bbc0f',
                           '--surface': '#9bbc0f',
                           '--card': '#8bac0f',
                           '--card-border': '#306230',
                           '--text': '#0f380f',
                           '--text-secondary': '#1a4a1a',
                           '--muted': '#306230',
                           '--good': '#0f380f',
                           '--warn': '#1a4a1a',
                           '--crit': '#3d1a00',
                           '--accent': '#0f380f',
                           '--accent-hover': '#1a4a1a',
                           '--accent-muted': 'rgba(15, 56, 15, 0.15)',
                           '--info': '#1a4a1a',
                           '--input-border': '#306230',
                           '--overlay': 'rgba(15, 56, 15, 0.4)',
                           '--hover-bg': 'rgba(15, 56, 15, 0.08)',
                           '--void': '#9bbc0f',
                           '--void-deep': '#8bac0f',
                           '--elevated': '#7a9c00',
                           '--hover': '#306230',
                           '--amethyst': '#0f380f',
                           '--amethyst-light': '#1a4a1a',
                           '--sapphire': '#1a4a1a',
                           '--glass-bg': 'rgba(155, 188, 15, 0.85)',
                           '--glass-border': 'rgba(15, 56, 15, 0.1)'}}},
 {'id': 'docsight.theme_gruvbox',
  'name': 'Gruvbox',
  'description': "Warm retro earth tones inspired by Gruvbox's wood-and-amber palette",
  'version': '1.0.0',
  'author': 'itsDNNS',
  'minAppVersion': '2026.2',
  'theme_data': {'meta': {'family': 'community-favorite', 'collection': 'community'},
                 'dark': {'--bg': '#282828',
                          '--surface': '#32302f',
                          '--card': '#3c3836',
                          '--card-border': 'rgba(215, 153, 33, 0.16)',
                          '--text': '#ebdbb2',
                          '--text-secondary': '#d5c4a1',
                          '--muted': '#928374',
                          '--good': '#b8bb26',
                          '--warn': '#fabd2f',
                          '--crit': '#fb4934',
                          '--accent': '#d79921',
                          '--accent-hover': '#fe8019',
                          '--accent-muted': 'rgba(215, 153, 33, 0.16)',
                          '--info': '#83a598',
                          '--input-border': 'rgba(215, 153, 33, 0.18)',
                          '--overlay': 'rgba(20, 17, 15, 0.72)',
                          '--hover-bg': 'rgba(215, 153, 33, 0.08)',
                          '--void': '#1d2021',
                          '--void-deep': '#171919',
                          '--elevated': '#504945',
                          '--hover': '#665c54',
                          '--amethyst': '#d3869b',
                          '--amethyst-light': '#ebdbb2',
                          '--sapphire': '#83a598',
                          '--glass-bg': 'rgba(40, 40, 40, 0.85)',
                          '--glass-border': 'rgba(215, 153, 33, 0.1)'},
                 'light': {'--bg': '#fbf1c7',
                           '--surface': '#f2e5bc',
                           '--card': '#f9f5d7',
                           '--card-border': 'rgba(175, 105, 0, 0.16)',
                           '--text': '#3c3836',
                           '--text-secondary': '#504945',
                           '--muted': '#928374',
                           '--good': '#79740e',
                           '--warn': '#b57614',
                           '--crit': '#cc241d',
                           '--accent': '#af3a03',
                           '--accent-hover': '#9d3100',
                           '--accent-muted': 'rgba(175, 58, 3, 0.1)',
                           '--info': '#076678',
                           '--input-border': 'rgba(175, 58, 3, 0.14)',
                           '--overlay': 'rgba(0, 0, 0, 0.25)',
                           '--hover-bg': 'rgba(175, 58, 3, 0.05)',
                           '--void': '#fbf1c7',
                           '--void-deep': '#f2e5bc',
                           '--elevated': '#ebdbb2',
                           '--hover': '#d5c4a1',
                           '--amethyst': '#8f3f71',
                           '--amethyst-light': '#b16286',
                           '--sapphire': '#076678',
                           '--glass-bg': 'rgba(249, 245, 215, 0.86)',
                           '--glass-border': 'rgba(175, 58, 3, 0.08)'}}},
 {'id': 'docsight.theme_matrix',
  'name': 'Matrix',
  'description': 'Phosphor green on black — enter the Matrix',
  'version': '1.0.0',
  'author': 'itsDNNS',
  'minAppVersion': '2026.2',
  'theme_data': {'meta': {'family': 'dark-first'},
                 'dark': {'--bg': '#0a0a0a',
                          '--surface': '#0f0f0f',
                          '--card': '#111111',
                          '--card-border': 'rgba(0, 255, 65, 0.12)',
                          '--text': '#00ff41',
                          '--text-secondary': '#00cc33',
                          '--muted': '#008020',
                          '--good': '#00ff41',
                          '--warn': '#ccff00',
                          '--crit': '#ff0040',
                          '--accent': '#00ff41',
                          '--accent-hover': '#33ff66',
                          '--accent-muted': 'rgba(0, 255, 65, 0.12)',
                          '--info': '#00ccff',
                          '--input-border': 'rgba(0, 255, 65, 0.18)',
                          '--overlay': 'rgba(0, 0, 0, 0.8)',
                          '--hover-bg': 'rgba(0, 255, 65, 0.06)',
                          '--void': '#050505',
                          '--void-deep': '#000000',
                          '--elevated': '#1a1a1a',
                          '--hover': '#222222',
                          '--amethyst': '#00ff41',
                          '--amethyst-light': '#66ff88',
                          '--sapphire': '#00ccff',
                          '--glass-bg': 'rgba(10, 10, 10, 0.9)',
                          '--glass-border': 'rgba(0, 255, 65, 0.1)',
                          '--font-sans': "'Courier New', 'Consolas', monospace",
                          '--font-mono': "'Courier New', 'Consolas', monospace"},
                 'light': {'--bg': '#e8ffe8',
                           '--surface': '#e8ffe8',
                           '--card': '#d4f5d4',
                           '--card-border': '#a0d8a0',
                           '--text': '#003310',
                           '--text-secondary': '#1a5c30',
                           '--muted': '#5a9a6a',
                           '--good': '#008030',
                           '--warn': '#7a8c00',
                           '--crit': '#cc0033',
                           '--accent': '#008030',
                           '--accent-hover': '#006625',
                           '--accent-muted': 'rgba(0, 128, 48, 0.1)',
                           '--info': '#007099',
                           '--input-border': '#a0d8a0',
                           '--overlay': 'rgba(0, 0, 0, 0.4)',
                           '--hover-bg': 'rgba(0, 128, 48, 0.05)',
                           '--void': '#e8ffe8',
                           '--void-deep': '#d4f5d4',
                           '--elevated': '#c0ebc0',
                           '--hover': '#a8dca8',
                           '--amethyst': '#008030',
                           '--amethyst-light': '#00a040',
                           '--sapphire': '#007099',
                           '--glass-bg': 'rgba(232, 255, 232, 0.85)',
                           '--glass-border': 'rgba(0, 128, 48, 0.08)',
                           '--font-sans': "'Courier New', 'Consolas', monospace",
                           '--font-mono': "'Courier New', 'Consolas', monospace"}}},
 {'id': 'docsight.theme_nord',
  'name': 'Nord',
  'description': 'Cool arctic blue palette — clean and calm',
  'version': '1.0.0',
  'author': 'itsDNNS',
  'minAppVersion': '2026.2',
  'theme_data': {'meta': {'family': 'dark-first'},
                 'dark': {'--bg': '#2e3440',
                          '--surface': '#3b4252',
                          '--card': '#3b4252',
                          '--card-border': 'rgba(136, 192, 208, 0.12)',
                          '--text': '#eceff4',
                          '--text-secondary': '#d8dee9',
                          '--muted': '#4c566a',
                          '--good': '#a3be8c',
                          '--warn': '#ebcb8b',
                          '--crit': '#bf616a',
                          '--accent': '#88c0d0',
                          '--accent-hover': '#8fbcbb',
                          '--accent-muted': 'rgba(136, 192, 208, 0.15)',
                          '--info': '#81a1c1',
                          '--input-border': 'rgba(136, 192, 208, 0.18)',
                          '--overlay': 'rgba(46, 52, 64, 0.7)',
                          '--hover-bg': 'rgba(136, 192, 208, 0.06)',
                          '--void': '#242933',
                          '--void-deep': '#1d2128',
                          '--elevated': '#434c5e',
                          '--hover': '#4c566a',
                          '--amethyst': '#b48ead',
                          '--amethyst-light': '#c9a3c2',
                          '--sapphire': '#81a1c1',
                          '--glass-bg': 'rgba(46, 52, 64, 0.85)',
                          '--glass-border': 'rgba(136, 192, 208, 0.1)'},
                 'light': {'--bg': '#eceff4',
                           '--surface': '#e5e9f0',
                           '--card': '#e5e9f0',
                           '--card-border': '#d8dee9',
                           '--text': '#2e3440',
                           '--text-secondary': '#3b4252',
                           '--muted': '#7b88a1',
                           '--good': '#6d8a5e',
                           '--warn': '#c49543',
                           '--crit': '#a5434c',
                           '--accent': '#5e81ac',
                           '--accent-hover': '#4c7099',
                           '--accent-muted': 'rgba(94, 129, 172, 0.1)',
                           '--info': '#5e81ac',
                           '--input-border': '#d8dee9',
                           '--overlay': 'rgba(0, 0, 0, 0.35)',
                           '--hover-bg': 'rgba(94, 129, 172, 0.05)',
                           '--void': '#eceff4',
                           '--void-deep': '#e5e9f0',
                           '--elevated': '#d8dee9',
                           '--hover': '#c8d0dc',
                           '--amethyst': '#9a6e94',
                           '--amethyst-light': '#b48ead',
                           '--sapphire': '#5e81ac',
                           '--glass-bg': 'rgba(236, 239, 244, 0.85)',
                           '--glass-border': 'rgba(94, 129, 172, 0.08)'}}},
 {'id': 'docsight.theme_ocean',
  'name': 'Ocean',
  'description': 'Deep navy with teal and cyan accents',
  'version': '1.0.0',
  'author': 'itsDNNS',
  'minAppVersion': '2026.2',
  'theme_data': {'meta': {'family': 'dark-first'},
                 'dark': {'--bg': '#0a1628',
                          '--surface': '#0f1d32',
                          '--card': '#0f1d32',
                          '--card-border': 'rgba(6, 182, 212, 0.12)',
                          '--text': '#e0f2fe',
                          '--text-secondary': '#7dd3fc',
                          '--muted': '#38bdf8',
                          '--good': '#2dd4bf',
                          '--warn': '#fbbf24',
                          '--crit': '#f87171',
                          '--accent': '#06b6d4',
                          '--accent-hover': '#0891b2',
                          '--accent-muted': 'rgba(6, 182, 212, 0.15)',
                          '--info': '#0ea5e9',
                          '--input-border': 'rgba(6, 182, 212, 0.15)',
                          '--overlay': 'rgba(0, 0, 0, 0.7)',
                          '--hover-bg': 'rgba(255, 255, 255, 0.05)',
                          '--void': '#0a1628',
                          '--void-deep': '#060f1e',
                          '--elevated': '#132640',
                          '--hover': '#1a3352',
                          '--amethyst': '#06b6d4',
                          '--amethyst-light': '#22d3ee',
                          '--sapphire': '#0ea5e9',
                          '--glass-bg': 'rgba(10, 22, 40, 0.7)',
                          '--glass-border': 'rgba(6, 182, 212, 0.12)'},
                 'light': {'--bg': '#f0f9ff',
                           '--surface': '#ffffff',
                           '--card': '#f0f9ff',
                           '--card-border': 'rgba(8, 145, 178, 0.15)',
                           '--text': '#0c4a6e',
                           '--text-secondary': '#0e7490',
                           '--muted': '#06b6d4',
                           '--good': '#0d9488',
                           '--warn': '#d97706',
                           '--crit': '#dc2626',
                           '--accent': '#0891b2',
                           '--accent-hover': '#0e7490',
                           '--accent-muted': 'rgba(8, 145, 178, 0.1)',
                           '--info': '#0284c7',
                           '--input-border': 'rgba(8, 145, 178, 0.15)',
                           '--overlay': 'rgba(0, 0, 0, 0.4)',
                           '--hover-bg': 'rgba(0, 0, 0, 0.03)',
                           '--void': '#f0f9ff',
                           '--void-deep': '#e0f2fe',
                           '--elevated': '#e0f2fe',
                           '--hover': '#bae6fd',
                           '--amethyst': '#0891b2',
                           '--amethyst-light': '#06b6d4',
                           '--sapphire': '#0284c7',
                           '--glass-bg': 'rgba(240, 249, 255, 0.8)',
                           '--glass-border': 'rgba(8, 145, 178, 0.12)'}}},
 {'id': 'docsight.theme_one_dark',
  'name': 'One Dark',
  'description': 'Balanced charcoal blues inspired by the One Dark and One Light pair',
  'version': '1.0.0',
  'author': 'itsDNNS',
  'minAppVersion': '2026.2',
  'theme_data': {'meta': {'family': 'community-favorite', 'collection': 'community'},
                 'dark': {'--bg': '#1e2127',
                          '--surface': '#282c34',
                          '--card': '#2c313c',
                          '--card-border': 'rgba(97, 175, 239, 0.14)',
                          '--text': '#abb2bf',
                          '--text-secondary': '#9aa3b2',
                          '--muted': '#5c6370',
                          '--good': '#98c379',
                          '--warn': '#e5c07b',
                          '--crit': '#e06c75',
                          '--accent': '#61afef',
                          '--accent-hover': '#7fc0ff',
                          '--accent-muted': 'rgba(97, 175, 239, 0.14)',
                          '--info': '#56b6c2',
                          '--input-border': 'rgba(97, 175, 239, 0.18)',
                          '--overlay': 'rgba(17, 19, 24, 0.72)',
                          '--hover-bg': 'rgba(97, 175, 239, 0.08)',
                          '--void': '#17191f',
                          '--void-deep': '#111318',
                          '--elevated': '#353b45',
                          '--hover': '#3e4551',
                          '--amethyst': '#c678dd',
                          '--amethyst-light': '#d19a66',
                          '--sapphire': '#61afef',
                          '--glass-bg': 'rgba(30, 33, 39, 0.85)',
                          '--glass-border': 'rgba(97, 175, 239, 0.1)'},
                 'light': {'--bg': '#fafafa',
                           '--surface': '#ffffff',
                           '--card': '#f0f0f1',
                           '--card-border': 'rgba(64, 120, 242, 0.12)',
                           '--text': '#383a42',
                           '--text-secondary': '#5c6370',
                           '--muted': '#8a93a5',
                           '--good': '#50a14f',
                           '--warn': '#c18401',
                           '--crit': '#e45649',
                           '--accent': '#4078f2',
                           '--accent-hover': '#2f68e0',
                           '--accent-muted': 'rgba(64, 120, 242, 0.1)',
                           '--info': '#0184bc',
                           '--input-border': 'rgba(64, 120, 242, 0.14)',
                           '--overlay': 'rgba(0, 0, 0, 0.28)',
                           '--hover-bg': 'rgba(64, 120, 242, 0.04)',
                           '--void': '#fafafa',
                           '--void-deep': '#f0f0f1',
                           '--elevated': '#e5e5e6',
                           '--hover': '#d6d6d7',
                           '--amethyst': '#a626a4',
                           '--amethyst-light': '#986801',
                           '--sapphire': '#4078f2',
                           '--glass-bg': 'rgba(250, 250, 250, 0.86)',
                           '--glass-border': 'rgba(64, 120, 242, 0.08)'}}},
 {'id': 'docsight.theme_synthwave',
  'name': 'SynthWave',
  'description': 'Neon pink and cyan on deep violet — 80s retro futurism',
  'version': '1.0.0',
  'author': 'itsDNNS',
  'minAppVersion': '2026.2',
  'theme_data': {'meta': {'family': 'dark-first'},
                 'dark': {'--bg': '#1a1025',
                          '--surface': '#241535',
                          '--card': '#2a1a3e',
                          '--card-border': 'rgba(255, 42, 232, 0.15)',
                          '--text': '#f0e6ff',
                          '--text-secondary': '#b8a4d6',
                          '--muted': '#7a6699',
                          '--good': '#2ee8a5',
                          '--warn': '#ffe156',
                          '--crit': '#ff3860',
                          '--accent': '#ff2ae8',
                          '--accent-hover': '#e020d0',
                          '--accent-muted': 'rgba(255, 42, 232, 0.15)',
                          '--info': '#00d4ff',
                          '--input-border': 'rgba(255, 42, 232, 0.2)',
                          '--overlay': 'rgba(10, 5, 20, 0.7)',
                          '--hover-bg': 'rgba(255, 42, 232, 0.08)',
                          '--void': '#12091c',
                          '--void-deep': '#0a0512',
                          '--elevated': '#341f4a',
                          '--hover': '#3e2858',
                          '--amethyst': '#ff2ae8',
                          '--amethyst-light': '#ff6ef3',
                          '--sapphire': '#00d4ff',
                          '--glass-bg': 'rgba(26, 16, 37, 0.85)',
                          '--glass-border': 'rgba(255, 42, 232, 0.12)'},
                 'light': {'--bg': '#fdf5ff',
                           '--surface': '#fdf5ff',
                           '--card': '#f5eafc',
                           '--card-border': '#e8d0f5',
                           '--text': '#2a1040',
                           '--text-secondary': '#6b4d8a',
                           '--muted': '#9a80b5',
                           '--good': '#0dab76',
                           '--warn': '#c49200',
                           '--crit': '#d4204e',
                           '--accent': '#c520b0',
                           '--accent-hover': '#a01890',
                           '--accent-muted': 'rgba(197, 32, 176, 0.1)',
                           '--info': '#0098cc',
                           '--input-border': '#e0c8f0',
                           '--overlay': 'rgba(0, 0, 0, 0.4)',
                           '--hover-bg': 'rgba(197, 32, 176, 0.05)',
                           '--void': '#fdf5ff',
                           '--void-deep': '#f5eafc',
                           '--elevated': '#eedcf8',
                           '--hover': '#e0c8f0',
                           '--amethyst': '#c520b0',
                           '--amethyst-light': '#d840c8',
                           '--sapphire': '#0098cc',
                           '--glass-bg': 'rgba(253, 245, 255, 0.85)',
                           '--glass-border': 'rgba(197, 32, 176, 0.08)'}}},
 {'id': 'docsight.theme_tokyo_night',
  'name': 'Tokyo Night',
  'description': 'Cool midnight blues with neon highlights inspired by Tokyo Night',
  'version': '1.0.0',
  'author': 'itsDNNS',
  'minAppVersion': '2026.2',
  'theme_data': {'meta': {'family': 'community-favorite', 'collection': 'community'},
                 'dark': {'--bg': '#1a1b26',
                          '--surface': '#1f2335',
                          '--card': '#24283b',
                          '--card-border': 'rgba(122, 162, 247, 0.14)',
                          '--text': '#c0caf5',
                          '--text-secondary': '#a9b1d6',
                          '--muted': '#565f89',
                          '--good': '#9ece6a',
                          '--warn': '#e0af68',
                          '--crit': '#f7768e',
                          '--accent': '#7aa2f7',
                          '--accent-hover': '#89b4fa',
                          '--accent-muted': 'rgba(122, 162, 247, 0.14)',
                          '--info': '#2ac3de',
                          '--input-border': 'rgba(122, 162, 247, 0.18)',
                          '--overlay': 'rgba(15, 18, 30, 0.74)',
                          '--hover-bg': 'rgba(122, 162, 247, 0.08)',
                          '--void': '#16161e',
                          '--void-deep': '#101017',
                          '--elevated': '#292e42',
                          '--hover': '#343b58',
                          '--amethyst': '#bb9af7',
                          '--amethyst-light': '#c0caf5',
                          '--sapphire': '#7dcfff',
                          '--glass-bg': 'rgba(26, 27, 38, 0.86)',
                          '--glass-border': 'rgba(122, 162, 247, 0.1)'},
                 'light': {'--bg': '#d5d6db',
                           '--surface': '#cbccd1',
                           '--card': '#ffffff',
                           '--card-border': 'rgba(52, 84, 138, 0.14)',
                           '--text': '#3760bf',
                           '--text-secondary': '#6172b0',
                           '--muted': '#848cb5',
                           '--good': '#587539',
                           '--warn': '#8c6c3e',
                           '--crit': '#c64343',
                           '--accent': '#34548a',
                           '--accent-hover': '#2e4f89',
                           '--accent-muted': 'rgba(52, 84, 138, 0.1)',
                           '--info': '#0f4b6e',
                           '--input-border': 'rgba(52, 84, 138, 0.14)',
                           '--overlay': 'rgba(0, 0, 0, 0.3)',
                           '--hover-bg': 'rgba(52, 84, 138, 0.05)',
                           '--void': '#d5d6db',
                           '--void-deep': '#cbccd1',
                           '--elevated': '#bfc0c5',
                           '--hover': '#b3b4b9',
                           '--amethyst': '#5a4a78',
                           '--amethyst-light': '#7a5ea6',
                           '--sapphire': '#34548a',
                           '--glass-bg': 'rgba(255, 255, 255, 0.8)',
                           '--glass-border': 'rgba(52, 84, 138, 0.08)'}}},
 {'id': 'docsight.theme_tribu',
  'name': 'Tribu',
  'description': 'Glass-morphism design with void-dark palette and amethyst accents — inspired by Tribu',
  'version': '1.0.0',
  'author': 'itsDNNS',
  'homepage': 'https://github.com/itsDNNS/tribu',
  'minAppVersion': '2026.2',
  'theme_data': {'meta': {'family': 'dark-first'},
                 'dark': {'--bg': '#06080f',
                          '--surface': '#111628',
                          '--card': '#111628',
                          '--card-border': 'rgba(120, 130, 180, 0.12)',
                          '--text': '#e8edff',
                          '--text-secondary': '#9ba3c8',
                          '--muted': '#7880a6',
                          '--good': '#10b981',
                          '--warn': '#f59e0b',
                          '--crit': '#ef4444',
                          '--accent': '#7c3aed',
                          '--accent-hover': '#6d28d9',
                          '--accent-muted': 'rgba(124, 58, 237, 0.15)',
                          '--info': '#3b82f6',
                          '--input-border': 'rgba(120, 130, 180, 0.12)',
                          '--overlay': 'rgba(0, 0, 0, 0.7)',
                          '--hover-bg': 'rgba(255, 255, 255, 0.05)',
                          '--void': '#06080f',
                          '--void-deep': '#0a0d18',
                          '--elevated': '#181e35',
                          '--hover': '#1f2847',
                          '--amethyst': '#7c3aed',
                          '--amethyst-light': '#a78bfa',
                          '--sapphire': '#3b82f6',
                          '--glass-bg': 'rgba(17, 22, 40, 0.65)',
                          '--glass-border': 'rgba(120, 130, 180, 0.12)'},
                 'light': {'--bg': '#f8f6f3',
                           '--surface': '#ffffff',
                           '--card': '#ffffff',
                           '--card-border': 'rgba(120, 100, 160, 0.15)',
                           '--text': '#1a1520',
                           '--text-secondary': '#5e5673',
                           '--muted': '#8a82a0',
                           '--good': '#059669',
                           '--warn': '#d97706',
                           '--crit': '#dc2626',
                           '--accent': '#7c3aed',
                           '--accent-hover': '#6d28d9',
                           '--accent-muted': 'rgba(124, 58, 237, 0.1)',
                           '--info': '#2563eb',
                           '--input-border': 'rgba(120, 100, 160, 0.15)',
                           '--overlay': 'rgba(0, 0, 0, 0.5)',
                           '--hover-bg': 'rgba(0, 0, 0, 0.03)',
                           '--void': '#f8f6f3',
                           '--void-deep': '#f0edf5',
                           '--elevated': '#f0edf5',
                           '--hover': '#e8e4f0',
                           '--amethyst': '#7c3aed',
                           '--amethyst-light': '#a78bfa',
                           '--sapphire': '#3b82f6',
                           '--glass-bg': 'rgba(255, 255, 255, 0.7)',
                           '--glass-border': 'rgba(120, 100, 160, 0.15)'}}})


def fetch_registry(registry_url: str, timeout: int = 10) -> list[dict]:
    """Fetch the theme registry index and return list of valid theme entries."""
    return _fetch_registry(registry_url, key="themes", timeout=timeout)


def download_theme(download_url: str, target_dir: str, timeout: int = 30) -> bool:
    """Download a theme module from the registry into target_dir.

    Uses the generic directory downloader, then validates that both
    manifest.json and theme.json exist.
    """
    if not download_github_directory(download_url, target_dir, timeout):
        return False

    manifest_path = safe_child_file(target_dir, "manifest.json")
    theme_path = safe_child_file(target_dir, "theme.json")
    if not os.path.isfile(manifest_path) or not os.path.isfile(theme_path):
        log.error("Downloaded theme missing manifest.json or theme.json")
        shutil.rmtree(target_dir, ignore_errors=True)
        return False

    return True
