"""Shared type definitions for DOCSight.

Central home for TypedDicts that describe data shapes flowing between
subsystems (drivers, analyzer, storage, web, collectors, event detector).

These are type-checking-only annotations -- they add zero runtime overhead
and do not change any public API, config key, DB schema, or wire format.
"""

from __future__ import annotations

from typing import Any, NotRequired, TypedDict


# ── Raw DOCSIS Channel (driver output, pre-analysis) ────────────


class RawChannel(TypedDict, total=False):
    """A single raw channel dict as returned by modem drivers.

    Keys vary by driver; all are optional.  The analyzer normalises
    these into DownstreamChannel / UpstreamChannel after analysis.
    """

    channelID: int | float | str
    frequency: str
    powerLevel: float | str | None
    modulation: str
    type: str
    mse: float | str | None          # DS 3.0 signal-to-noise (negative dB)
    mer: float | str | None           # DS 3.1 MER
    corrErrors: int | None
    nonCorrErrors: int | None
    symbolRate: int | None
    multiplex: str
    profile_modulation: str


class _DocsisVersionChannels(TypedDict, total=False):
    """Channel lists keyed by DOCSIS version (FritzBox format)."""

    docsis30: list[RawChannel]
    docsis31: list[RawChannel]


class DocsisDataFritz(TypedDict):
    """FritzBox-style DOCSIS payload (channelDs/channelUs sub-dicts)."""

    channelDs: _DocsisVersionChannels
    channelUs: _DocsisVersionChannels


class DocsisDataFlat(TypedDict):
    """Flat DOCSIS payload used by TC4400, Ultra Hub 7, Vodafone Station, etc."""

    docsis: str                      # "3.0" or "3.1"
    downstream: list[RawChannel]
    upstream: list[RawChannel]


DocsisData = DocsisDataFritz | DocsisDataFlat
"""Union of the two raw DOCSIS formats accepted by analyzer.analyze()."""


# ── DOCSIS Channel Types (output of analyzer.analyze()) ──────────


class DownstreamChannel(TypedDict):
    """A single downstream channel after analysis."""

    channel_id: int
    frequency: str
    power: float | None
    modulation: str
    snr: float | None
    correctable_errors: int | None
    uncorrectable_errors: int | None
    docsis_version: str
    health: str
    health_detail: str
    # Optional per-metric health keys (present when health_detail is non-empty)
    power_health: NotRequired[str]
    snr_health: NotRequired[str]
    modulation_health: NotRequired[str]
    # Optional profile modulation (driver-specific)
    profile_modulation: NotRequired[str]


class UpstreamChannel(TypedDict):
    """A single upstream channel after analysis."""

    channel_id: int
    frequency: str
    power: float | None
    modulation: str
    multiplex: str
    docsis_version: str
    health: str
    health_detail: str
    theoretical_bitrate: float | None
    # Optional per-metric health keys
    power_health: NotRequired[str]
    modulation_health: NotRequired[str]
    # Optional profile modulation (driver-specific)
    profile_modulation: NotRequired[str]


# ── Spike Suppression ────────────────────────────────────────────


class SpikeSuppression(TypedDict):
    """Spike suppression metadata set by apply_spike_suppression()."""

    active: bool
    last_spike: str
    hours_since_spike: float
    expiry_hours: int


# ── Analysis Summary ─────────────────────────────────────────────


class AnalysisSummary(TypedDict):
    """Summary metrics from analyzer.analyze()."""

    ds_total: int
    us_total: int
    ds_power_min: float
    ds_power_max: float
    ds_power_avg: float
    us_power_min: float
    us_power_max: float
    us_power_avg: float
    ds_snr_min: float
    ds_snr_max: float
    ds_snr_avg: float
    ds_correctable_errors: int | None
    ds_uncorrectable_errors: int | None
    errors_supported: bool
    us_capacity_mbps: float | None
    ds_uncorr_pct: float | None
    health: str
    health_issues: list[str]
    # Set by apply_spike_suppression() when active
    spike_suppression: NotRequired[SpikeSuppression]


# ── Full Analysis Result ─────────────────────────────────────────


class AnalysisResult(TypedDict):
    """Complete result from analyzer.analyze().

    This is the primary data structure flowing through the system:
    analyzer -> collector -> storage/web/mqtt/events/prometheus.
    """

    summary: AnalysisSummary
    ds_channels: list[DownstreamChannel]
    us_channels: list[UpstreamChannel]


# ── Event Types ──────────────────────────────────────────────────


class EventDict(TypedDict):
    """An event generated by EventDetector or module collectors.

    Consumed by: storage.save_events(), notifier.dispatch(),
    smart_capture.evaluate().
    """

    timestamp: str
    severity: str  # "info" | "warning" | "critical"
    event_type: str
    message: str
    details: NotRequired[dict[str, Any] | None]
    # Set by save_events_with_ids() after DB insert
    _id: NotRequired[int]


# ── Driver Return Types ──────────────────────────────────────────


class DeviceInfo(TypedDict, total=False):
    """Device information returned by ModemDriver.get_device_info().

    All keys are optional since driver capabilities vary widely.
    """

    manufacturer: str
    model: str
    hw_version: str     # hardware version/revision
    sw_version: str     # firmware/software version
    docsis_status: str  # e.g. online/offline/syncing
    uptime_seconds: int
    reboot_reason: str  # reason for the last reboot
    wan_ipv4: str
    wan_ipv6: str


class ConnectionInfo(TypedDict, total=False):
    """Connection information returned by ModemDriver.get_connection_info().

    Empty dict is valid (standalone modems without WAN info).
    """

    max_downstream_kbps: int
    max_upstream_kbps: int
    connection_type: str
    wan_ip: str
    status: str


# ── Collector Status ─────────────────────────────────────────────


class CollectorStatus(TypedDict):
    """Health status dict returned by Collector.get_status()."""

    name: str
    enabled: bool
    consecutive_failures: int
    penalty_seconds: int
    poll_interval: int
    effective_interval: float
    last_poll: float
    next_poll_in: int


# ── Gaming Quality Index ─────────────────────────────────────────


class GamingIndexComponent(TypedDict):
    score: int
    weight: int


class GamingIndex(TypedDict):
    """Result from compute_gaming_index()."""

    score: int
    grade: str  # "A" | "B" | "C" | "D" | "F"
    components: dict[str, GamingIndexComponent]
    has_speedtest: bool


# ── Notification Payload ─────────────────────────────────────────


class NotificationPayload(TypedDict):
    """Payload sent to notification channels."""

    source: str
    timestamp: str
    severity: str
    event_type: str
    message: str
    details: dict[str, Any]


class NotificationTestResult(TypedDict):
    """Result from NotificationDispatcher.test()."""

    success: bool
    error: NotRequired[str]


# ── Module Download ─────────────────────────────────────────────


class RegistryEntry(TypedDict, total=False):
    """A single entry from the community module registry."""

    id: str
    name: str
    description: str
    version: str
    author: str
    download_url: str
    min_app_version: str
    url: str
    type: str


# ── Smart Capture Trigger Matching ──────────────────────────────


class TriggerRequireDetails(TypedDict, total=False):
    """Key/value pairs required in event details for a trigger to match."""


# ── Connection Monitor ──────────────────────────────────────────


class ProbeCapabilityInfo(TypedDict):
    """Probe method info returned by ConnectionProbe.capability_info()."""

    method: str
    reason: NotRequired[str]
    hint: NotRequired[str]


class ConnectionSummary(TypedDict, total=False):
    """Aggregated connection statistics from get_summary()."""

    sample_count: int
    avg_latency_ms: float | None
    min_latency_ms: float | None
    max_latency_ms: float | None
    packet_loss_pct: float | None


class ConnectionRangeStats(TypedDict, total=False):
    """Range statistics from get_range_stats()."""

    sample_count: int
    latency_count: int
    avg_latency_ms: float | None
    min_latency_ms: float | None
    max_latency_ms: float | None
    packet_loss_pct: float | None
    p95_latency_ms: float | None


class ConnectionOutage(TypedDict):
    """An outage derived from consecutive timeout sequences."""

    start: float
    end: float | None
    duration_seconds: float
    timeout_count: int


# ── Driver Hints ────────────────────────────────────────────────


class DriverHints(TypedDict, total=False):
    """UI hints for a modem driver (login fields, help text, etc.)."""

    needs_user: bool
    needs_password: bool
    default_url: str
    default_user: str
    username_required: bool
    credentials_required: bool
    url_hint: str
    user_hint: str
    password_hint: str
